// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package controllers

import (
	"test/internal"
)

// Injectors from wire.go:

func initControllers(app *test.App) *Controllers {
	pingController := providePingController(app)
	esimController := provideEsimController(app)
	demoController := provideDemoController(app)
	serverNodeController := provideServerController(app)
	controllers := &Controllers{
		App:        app,
		Ping:       pingController,
		Esim:       esimController,
		Demo:       demoController,
		ServerNode: serverNodeController,
	}
	return controllers
}
