// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package controllers

import (
	"test/internal"
)

// Injectors from wire.go:

func initControllers(app *test.App) *Controllers {
	tcpNodeController := providePingController(app)
	controllers := &Controllers{
		App:        app,
		ServerNode: tcpNodeController,
	}
	return controllers
}
